# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for backend
        run: sudo npm install

      - name: Install dependencies for frontend
        run: sudo npm install
        working-directory: ./client

      # - name: Run the tests for frontend
      #   run: sudo npm test --a --watchAll=false
      #   working-directory: ./client

      - name: Build the frontend
        run: sudo npm run build
        working-directory: ./client
